Repository laminas/laminas-validator, pull requests merged in 2020-02, with the labels that each got.

#51 Fix some minors typos
  bin/update_hostname_validator.php
Labels: Bug

#52 Refactor reduce complexity
  src/EmailAddress.php
Labels: Enhancement

#56 Missing end quote in sample code
  docs/book/validators/date.md
Labels: Bug, Documentation

#55 Validators "Using a Select object" example is invalid
  docs/book/validators/db.md
Labels: Bug, Documentation
