Repository laminas/laminas-validator, pull requests merged in 2021-01, with the labels that each got.

#75 PHP 8.0 support
  .travis.yml
  composer.json
  phpunit.xml.dist
  src/InArray.php
  test/BarcodeTest.php
  test/BetweenTest.php
  test/CallbackTest.php
  test/CreditCardTest.php
  test/DateStepTest.php
  test/DateTest.php
  test/Db/AbstractDbTest.php
  test/Db/NoRecordExistsTest.php
  test/Db/RecordExistsTest.php
  test/DigitsTest.php
  test/EmailAddressTest.php
  test/ExplodeTest.php
  test/File/FileInformationTraitTest.php
  test/File/UploadTest.php
  test/GreaterThanTest.php
  test/HexTest.php
  test/HostnameTest.php
  test/IbanTest.php
  test/IdenticalTest.php
  test/InArrayTest.php
  test/IpTest.php
  test/IsbnTest.php
  test/LessThanTest.php
  test/MessageTest.php
  test/NotEmptyTest.php
  test/RegexTest.php
  test/StepTest.php
  test/StringLengthTest.php
  test/UriTest.php
  test/ValidatorPluginManagerFactoryTest.php
  test/ValidatorPluginManagerTest.php
Labels: Enhancement, hacktoberfest-accepted

#63 qa: Replace array by data providers in unit tests for the hostname validator
  phpcs.xml
  test/HostnameTest.php
Labels: Enhancement

#71 Fix php-fig.org "PSR-7 UploadedFileInterface" link
  docs/book/validators/file/upload.md
Labels: Documentation, Enhancement

#58 feat: Add the support for SWIFT Business Identifier Code (BIC) format
  docs/book/validators/bic.md
  phpcs.xml
  src/BusinessIdentifierCode.php
  test/BusinessIdentifierCodeTest.php
Labels: Enhancement

#72 Fixed parameter types
  .travis.yml
  composer.json
  src/AbstractValidator.php
  src/BusinessIdentifierCode.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: Bug, Documentation

#77 add heic to valid isImage mime checks
  src/File/IsImage.php
Labels: Enhancement

#82 Removed unreachable code
  src/Sitemap/Changefreq.php
Labels: Enhancement

#83 Fix regression regarding InArray validator with boolean strict options
  CHANGELOG.md
  src/InArray.php
  test/InArrayTest.php
Labels: BC Break, Bug

#87 Removed hardcoded `version` field from `composer.json`
  composer.json
Labels: Bug

#89 Fix Type Error when validating a `DateTimeImmutable` instance to the `DateStep` validator
  src/Date.php
  src/DateStep.php
  test/DateStepTest.php
Labels: Bug

#91 Fix immutability issue when validating a `DateTimeImmutable` instance with the `DateStep` validator
  src/DateStep.php
  test/DateStepTest.php
Labels: Bug
