Repository laminas/laminas-validator, pull requests merged in 2021-07, with the labels that each got.

#93 Fix psalm errors on Date and DateStep validator
  psalm-baseline.xml
  src/Date.php
  src/DateStep.php
  src/Sitemap/Changefreq.php
  test/DateStepTest.php
  test/DateTest.php
Labels: Bug

#94 Adds page and configuration for installation
  docs/book/installation.md
  mkdocs.yml
Labels: Documentation, Enhancement

#100 Add docs for csrf validator to 2.14.x
  docs/book/set.md
  docs/book/validators/csrf.md
  mkdocs.yml
Labels: Documentation, Enhancement

#54 Remove deprecated assertion usage
  test/BarcodeTest.php
  test/BetweenTest.php
  test/CallbackTest.php
  test/CreditCardTest.php
  test/DateStepTest.php
  test/DateTest.php
  test/Db/NoRecordExistsTest.php
  test/Db/RecordExistsTest.php
  test/DigitsTest.php
  test/EmailAddressTest.php
  test/ExplodeTest.php
  test/GreaterThanTest.php
  test/HexTest.php
  test/HostnameTest.php
  test/IbanTest.php
  test/IdenticalTest.php
  test/InArrayTest.php
  test/IpTest.php
  test/IsbnTest.php
  test/LessThanTest.php
  test/MessageTest.php
  test/NotEmptyTest.php
  test/RegexTest.php
  test/StringLengthTest.php
  test/UriTest.php
Labels: Enhancement

#103 Update TLD list according to IANA 2021061501
  src/Hostname.php
Labels: Enhancement
