Repository laminas/laminas-validator, pull requests merged in 2022-07, with the labels that each got.

#136 Updates wrong MkDocs configuration for installation page and adds missing page for BIC validator
  mkdocs.yml
Labels: Bug, Documentation

#142 Update Hostname tlds to IanaVersion 2022072400
  src/Hostname.php
Labels: Enhancement

#144 Apply PHP 7.4 syntax and typed property
  src/Between.php
  src/CreditCard.php
  src/DateStep.php
  src/File/Upload.php
  src/IsCountable.php
  src/UndisclosedPassword.php
  test/BetweenTest.php
  test/CallbackTest.php
  test/DateTest.php
  test/ExplodeTest.php
  test/File/CountTest.php
  test/File/FilesSizeTest.php
  test/File/MimeTypeTest.php
  test/File/SizeTest.php
  test/File/WordCountTest.php
  test/IsCountableTest.php
  test/TestAsset/CustomTraversable.php
  test/TestAsset/Db/Join.php
  test/TestAsset/Uri/Uri.php
  test/UndisclosedPasswordTest.php
  test/UuidTest.php
  test/ValidatorChainTest.php
  test/ValidatorPluginManagerFactoryTest.php
  test/ValidatorPluginManagerTest.php
Labels: Enhancement

#145 Rolback // phpcs:enable and add return type declaration on ArrowFunction and Closure
  src/UndisclosedPassword.php
  test/CallbackTest.php
  test/TestAsset/Uri/Uri.php
  test/ValidatorChainTest.php
Labels: Documentation, Enhancement
