Repository laminas/laminas-validator, pull requests merged in 2024-06, with the labels that each got.

#245 Remove obsolete PHP 8.1 shims
  composer.json
  test/TestAsset/Db/AbstractResultSet.php
  test/TestAsset/Db/Join.php
  test/TestAsset/Db/ParameterContainer.php
  test/TestAsset/Db/PredicateSet.php
  test/TestAsset/Db/ResultSet.php
  test/TestAsset/Session/ArrayStorage.php
  test/TestAsset/Uri/Uri.php
  test/autoload.php
Labels: Enhancement

#244 Version current docs tree for future v3
  docs/book/v2/installation.md
  docs/book/v2/intro.md
  docs/book/v2/messages.md
  docs/book/v2/set.md
  docs/book/v2/validator-chains.md
  docs/book/v2/validators/barcode.md
  docs/book/v2/validators/between.md
  docs/book/v2/validators/bic.md
  docs/book/v2/validators/callback.md
  docs/book/v2/validators/credit-card.md
  docs/book/v2/validators/csrf.md
  docs/book/v2/validators/date.md
  docs/book/v2/validators/db.md
  docs/book/v2/validators/digits.md
  docs/book/v2/validators/email-address.md
  docs/book/v2/validators/explode.md
  docs/book/v2/validators/file/count.md
  docs/book/v2/validators/file/crc32.md
  docs/book/v2/validators/file/exclude-extension.md
  docs/book/v2/validators/file/exclude-mime-type.md
  docs/book/v2/validators/file/exists.md
  docs/book/v2/validators/file/extension.md
  docs/book/v2/validators/file/files-size.md
  docs/book/v2/validators/file/hash.md
  docs/book/v2/validators/file/image-size.md
  docs/book/v2/validators/file/intro.md
  docs/book/v2/validators/file/is-compressed.md
  docs/book/v2/validators/file/is-image.md
  docs/book/v2/validators/file/md5.md
  docs/book/v2/validators/file/mime-type.md
  docs/book/v2/validators/file/not-exists.md
  docs/book/v2/validators/file/sha1.md
  docs/book/v2/validators/file/size.md
  docs/book/v2/validators/file/upload-file.md
  docs/book/v2/validators/file/upload.md
  docs/book/v2/validators/file/word-count.md
  docs/book/v2/validators/greater-than.md
  docs/book/v2/validators/hex.md
  docs/book/v2/validators/hostname.md
  docs/book/v2/validators/iban.md
  docs/book/v2/validators/identical.md
  docs/book/v2/validators/in-array.md
  docs/book/v2/validators/ip.md
  docs/book/v2/validators/is-array.md
  docs/book/v2/validators/is-countable.md
  docs/book/v2/validators/is-json-string.md
  docs/book/v2/validators/isbn.md
  docs/book/v2/validators/isinstanceof.md
  docs/book/v2/validators/less-than.md
  docs/book/v2/validators/not-empty.md
  docs/book/v2/validators/regex.md
  docs/book/v2/validators/sitemap.md
  docs/book/v2/validators/step.md
  docs/book/v2/validators/string-length.md
  docs/book/v2/validators/timezone.md
  docs/book/v2/validators/undisclosed-password.md
  docs/book/v2/validators/uri.md
  docs/book/v2/validators/uuid.md
  docs/book/v2/writing-validators.md
  mkdocs.yml
Labels: Documentation

#224 Allow use of `TranslatorInterface` as Translator
  psalm-baseline.xml
  src/ConfigProvider.php
  src/Translator/DummyTranslator.php
  src/Translator/Translator.php
  src/Translator/TranslatorFactory.php
  src/ValidatorPluginManager.php
  test/Translator/TranslatorFactoryTest.php
  test/Translator/TranslatorTest.php
  test/ValidatorPluginManagerTest.php
Labels: Bug, Enhancement

#246 Checkout as 2.99.x so that cyclic dependencies can be installed
  .laminas-ci/pre-install.sh
Labels: Bug

#248 Duplicate v2 docs tree to v3
  docs/book/v3/installation.md
  docs/book/v3/intro.md
  docs/book/v3/messages.md
  docs/book/v3/set.md
  docs/book/v3/validator-chains.md
  docs/book/v3/validators/barcode.md
  docs/book/v3/validators/between.md
  docs/book/v3/validators/bic.md
  docs/book/v3/validators/callback.md
  docs/book/v3/validators/credit-card.md
  docs/book/v3/validators/csrf.md
  docs/book/v3/validators/date.md
  docs/book/v3/validators/db.md
  docs/book/v3/validators/digits.md
  docs/book/v3/validators/email-address.md
  docs/book/v3/validators/explode.md
  docs/book/v3/validators/file/count.md
  docs/book/v3/validators/file/crc32.md
  docs/book/v3/validators/file/exclude-extension.md
  docs/book/v3/validators/file/exclude-mime-type.md
  docs/book/v3/validators/file/exists.md
  docs/book/v3/validators/file/extension.md
  docs/book/v3/validators/file/files-size.md
  docs/book/v3/validators/file/hash.md
  docs/book/v3/validators/file/image-size.md
  docs/book/v3/validators/file/intro.md
  docs/book/v3/validators/file/is-compressed.md
  docs/book/v3/validators/file/is-image.md
  docs/book/v3/validators/file/md5.md
  docs/book/v3/validators/file/mime-type.md
  docs/book/v3/validators/file/not-exists.md
  docs/book/v3/validators/file/sha1.md
  docs/book/v3/validators/file/size.md
  docs/book/v3/validators/file/upload-file.md
  docs/book/v3/validators/file/upload.md
  docs/book/v3/validators/file/word-count.md
  docs/book/v3/validators/greater-than.md
  docs/book/v3/validators/hex.md
  docs/book/v3/validators/hostname.md
  docs/book/v3/validators/iban.md
  docs/book/v3/validators/identical.md
  docs/book/v3/validators/in-array.md
  docs/book/v3/validators/ip.md
  docs/book/v3/validators/is-array.md
  docs/book/v3/validators/is-countable.md
  docs/book/v3/validators/is-json-string.md
  docs/book/v3/validators/isbn.md
  docs/book/v3/validators/isinstanceof.md
  docs/book/v3/validators/less-than.md
  docs/book/v3/validators/not-empty.md
  docs/book/v3/validators/regex.md
  docs/book/v3/validators/sitemap.md
  docs/book/v3/validators/step.md
  docs/book/v3/validators/string-length.md
  docs/book/v3/validators/timezone.md
  docs/book/v3/validators/undisclosed-password.md
  docs/book/v3/validators/uri.md
  docs/book/v3/validators/uuid.md
  docs/book/v3/writing-validators.md
  mkdocs.yml
Labels: Documentation

#254 Remove dependency on laminas-filter
  composer.json
  composer.lock
  src/Digits.php
Labels: BC Break, Enhancement

#257 Add new Validator: `HostWithPublicIPv4Address`
  docs/book/v2/set.md
  docs/book/v2/validators/host-with-public-ipv4-address.md
  mkdocs.yml
  psalm-baseline.xml
  src/HostWithPublicIPv4Address.php
  src/ValidatorPluginManager.php
  test/HostWithPublicIPv4AddressTest.php
Labels: Enhancement, Feature Request

#258 Replace dated and flawed reserved ip checks in Email validator
  phpunit.xml.dist
  src/EmailAddress.php
  test/EmailAddressTest.php
  test/TestAsset/EmailValidatorWithExposedIsReserved.php
Labels: Enhancement

#259 Merge release 2.57.0 into 3.0
  docs/book/v2/set.md
  docs/book/v2/validators/host-with-public-ipv4-address.md
  mkdocs.yml
  phpunit.xml.dist
  psalm-baseline.xml
  src/EmailAddress.php
  src/HostWithPublicIPv4Address.php
  src/ValidatorPluginManager.php
  test/EmailAddressTest.php
  test/HostWithPublicIPv4AddressTest.php
  test/TestAsset/EmailValidatorWithExposedIsReserved.php
Labels: Enhancement

#261 Update v3 docs with changes from 2.57
  docs/book/v3/set.md
  docs/book/v3/validators/host-with-public-ipv4-address.md
  mkdocs.yml
Labels: Documentation

#262 Refactor URI Validator, Drop dependency on Laminas\Uri
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Sitemap/Loc.php
  src/Uri.php
  test/Sitemap/LocTest.php
  test/UriTest.php
Labels: BC Break, Enhancement

#265 Remove SMv2 Canonical FQCNs
  src/ValidatorPluginManager.php
Labels: Enhancement

#266 Remove i18n Validator aliases and factories
  src/ValidatorPluginManager.php
  test/StaticValidatorTest.php
Labels: BC Break, Enhancement

#268 Deprecate the CSRF validator
  docs/book/v2/validators/csrf.md
  psalm-baseline.xml
  src/Csrf.php
  test/CsrfTest.php
Labels: Documentation, Enhancement

#270 Remove the deprecated CSRF validator
  composer.json
  composer.lock
  docs/book/v3/set.md
  docs/book/v3/validators/csrf.md
  mkdocs.yml
  psalm-baseline.xml
  src/Csrf.php
  src/ValidatorPluginManager.php
  test/CsrfTest.php
  test/TestAsset/SessionManager.php
Labels: BC Break, Feature Removal

#271 Clean up IP validator
  psalm-baseline.xml
  src/Ip.php
  test/IpTest.php
Labels: BC Break

#273 Clean up Hex Validator
  psalm-baseline.xml
  src/Hex.php
  test/HexTest.php
Labels: BC Break, Enhancement

#282 Deprecate option setters and getters for the StringLength validator
  psalm-baseline.xml
  src/StringLength.php
Labels: Feature Removal

#283 Deprecate option setters and getters for the Regex validator
  psalm-baseline.xml
  src/Regex.php
Labels: Feature Removal

#277 Refactor Bitwise Validator
  psalm-baseline.xml
  src/Bitwise.php
  test/BitwiseTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Enhancement

#278 Refactor `StringLength` validator
  docs/book/v3/validators/string-length.md
  psalm-baseline.xml
  src/StringLength.php
  test/MessageTest.php
  test/StaticValidatorTest.php
  test/StringLengthTest.php
Labels: BC Break, Documentation, Enhancement

#279 UUID Validator Cleanup
  composer.lock
  src/Uuid.php
  test/UuidTest.php
Labels: BC Break, Enhancement

#280 Refactor `Regex` validator
  docs/book/v3/validators/regex.md
  psalm-baseline.xml
  src/Regex.php
  test/RegexTest.php
Labels: BC Break, Enhancement

#285 Callback validator deprecations
  psalm-baseline.xml
  src/Callback.php
Labels: Feature Removal

#287 Explode validator deprecations
  psalm-baseline.xml
  src/Explode.php
Labels: Feature Removal

#286 Refactor `Explode` validator
  docs/book/v3/validators/explode.md
  psalm-baseline.xml
  src/Explode.php
  test/ExplodeTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
  test/ValidatorPluginManagerTest.php
Labels: BC Break, Documentation, Enhancement

#284 Refactor `Callback` validator
  docs/book/v3/validators/callback.md
  psalm-baseline.xml
  src/Callback.php
  src/CreditCard.php
  test/CallbackTest.php
  test/ValidatorChainTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#276 Deprecate LessThan, GreaterThan and Between validators
  docs/book/v2/validators/between.md
  docs/book/v2/validators/greater-than.md
  docs/book/v2/validators/less-than.md
  psalm-baseline.xml
  src/Between.php
  src/GreaterThan.php
  src/LessThan.php
Labels: Documentation, Feature Removal

#288 Refactor `Timezone` validator
  docs/book/v3/validators/timezone.md
  psalm-baseline.xml
  src/Timezone.php
  test/TimezoneTest.php
Labels: BC Break, Documentation, Enhancement

#289 Deprecations for the `Timezone` validator
  psalm-baseline.xml
  src/Timezone.php
Labels: Feature Removal

#293 Deprecations for `Barcode` validator and adapters
  psalm-baseline.xml
  src/Barcode.php
  src/Barcode/AbstractAdapter.php
  src/Barcode/AdapterInterface.php
  src/Barcode/Code128.php
Labels: Feature Removal

#275 Introduce DateComparison validator
  docs/book/v2/set.md
  docs/book/v2/validators/date-comparison.md
  mkdocs.yml
  psalm-baseline.xml
  src/DateComparison.php
  src/ValidatorPluginManager.php
  test/DateComparisonTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: Documentation, Enhancement

#290 Remove the deprecated validators `LessThan`, `GreaterThan` and `Between`
  docs/book/v3/messages.md
  docs/book/v3/set.md
  docs/book/v3/validators/between.md
  docs/book/v3/validators/greater-than.md
  docs/book/v3/validators/less-than.md
  mkdocs.yml
  psalm-baseline.xml
  src/Between.php
  src/GreaterThan.php
  src/LessThan.php
  src/ValidatorPluginManager.php
  test/BetweenTest.php
  test/GreaterThanTest.php
  test/LessThanTest.php
  test/StaticValidatorTest.php
  test/ValidatorChainTest.php
Labels: BC Break, Documentation, Feature Removal

#291 Refactor `Barcode` validator
  docs/book/v3/validators/barcode.md
  psalm-baseline.xml
  src/Barcode.php
  src/Barcode/AbstractAdapter.php
  src/Barcode/AdapterInterface.php
  src/Barcode/Codabar.php
  src/Barcode/Code128.php
  src/Barcode/Code25.php
  src/Barcode/Code25interleaved.php
  src/Barcode/Code39.php
  src/Barcode/Code39ext.php
  src/Barcode/Code93.php
  src/Barcode/Code93ext.php
  src/Barcode/Ean12.php
  src/Barcode/Ean13.php
  src/Barcode/Ean14.php
  src/Barcode/Ean18.php
  src/Barcode/Ean2.php
  src/Barcode/Ean5.php
  src/Barcode/Ean8.php
  src/Barcode/Gtin12.php
  src/Barcode/Gtin13.php
  src/Barcode/Gtin14.php
  src/Barcode/Identcode.php
  src/Barcode/Intelligentmail.php
  src/Barcode/Issn.php
  src/Barcode/Itf14.php
  src/Barcode/Leitcode.php
  src/Barcode/Planet.php
  src/Barcode/Postnet.php
  src/Barcode/Royalmail.php
  src/Barcode/Sscc.php
  src/Barcode/Upca.php
  src/Barcode/Upce.php
  src/Barcode/Util.php
  test/BarcodeTest.php
  test/_files/MyBarcode1.php
  test/_files/MyBarcode2.php
  test/_files/MyBarcode3.php
  test/_files/MyBarcode4.php
  test/_files/MyBarcode5.php
Labels: BC Break, Documentation, Enhancement, Feature Removal
