Repository laminas/laminas-validator, pull requests merged in 2024-07, with the labels that each got.

#299 Deprecate option setters and getters in `Hostname`
  psalm-baseline.xml
  src/Hostname.php
Labels: Documentation, Feature Removal

#300 Backport `bind` feature for `Callback` validator
  docs/book/v2/validators/callback.md
  src/Callback.php
  test/CallbackTest.php
Labels: Documentation, Enhancement

#304 Refactor `IsInstanceOf` validator
  docs/book/v3/validators/isinstanceof.md
  psalm-baseline.xml
  src/IsInstanceOf.php
  test/IsInstanceOfTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Enhancement

#305 `IsInstanceOf` Deprecations
  psalm-baseline.xml
  src/IsInstanceOf.php
Labels: Documentation, Feature Removal

#301 Migrate to `Laminas\Translator`
  composer.json
  composer.lock
  psalm-baseline.xml
  src/AbstractValidator.php
  src/ConfigProvider.php
  src/EmailAddress.php
  src/Hostname.php
  src/Translator/DummyTranslator.php
  src/Translator/Translator.php
  src/Translator/TranslatorAwareInterface.php
  src/Translator/TranslatorFactory.php
  src/Translator/TranslatorInterface.php
  src/ValidatorPluginManager.php
  test/AbstractValidatorTest.php
  test/EmailAddressTest.php
  test/File/MimeTypeTest.php
  test/HostnameTest.php
  test/StaticValidatorTest.php
  test/TestAsset/ArrayTranslator.php
  test/TestAsset/Translator.php
  test/Translator/TranslatorFactoryTest.php
  test/Translator/TranslatorTest.php
  test/ValidatorPluginManagerTest.php
Labels: BC Break, Enhancement

#306 Deprecate Validator Specific Translator Classes
  psalm-baseline.xml
  src/Translator/DummyTranslator.php
  src/Translator/Translator.php
  src/Translator/TranslatorFactory.php
  src/Translator/TranslatorInterface.php
Labels: Documentation, Feature Removal

#308 `Step` validator deprecations
  psalm-baseline.xml
  src/Step.php
Labels: Documentation, Feature Removal

#307 Refactor `Step` validator
  psalm-baseline.xml
  src/Step.php
  test/StepTest.php
Labels: BC Break, Enhancement

#310 Deprecate the `StaticValidator`
  psalm-baseline.xml
  src/StaticValidator.php
Labels: Documentation, Feature Removal

#309 Remove `StaticValidator`
  psalm-baseline.xml
  src/StaticValidator.php
  test/StaticValidatorTest.php
Labels: BC Break, Feature Removal

#312 `NotEmpty` validator deprecations
  psalm-baseline.xml
  src/NotEmpty.php
Labels: Documentation, Feature Removal

#311 Refactor `NotEmpty` validator
  docs/book/v3/validators/not-empty.md
  psalm-baseline.xml
  src/NotEmpty.php
  test/NotEmptyTest.php
Labels: BC Break, Documentation, Enhancement

#313 `IsCountable` validator deprecations
  psalm-baseline.xml
  src/IsCountable.php
Labels: Documentation, Feature Removal

#298 Refactor `Hostname` validator
  docs/book/v3/validators/hostname.md
  psalm-baseline.xml
  src/EmailAddress.php
  src/Hostname.php
  test/EmailAddressTest.php
  test/HostnameTest.php
Labels: BC Break, Enhancement

#314 Refactor `IsCountable` validator
  docs/book/v3/validators/is-countable.md
  psalm-baseline.xml
  src/IsCountable.php
  test/IsCountableTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#267 Upgrade to Service Manager v4
  composer.json
  composer.lock
  psalm-baseline.xml
  src/ValidatorChain.php
  src/ValidatorPluginManager.php
  src/ValidatorPluginManagerFactory.php
  test/StaticAnalysis/PluginManager.php
  test/ValidatorPluginManagerCompatibilityTest.php
  test/ValidatorPluginManagerFactoryTest.php
  test/ValidatorPluginManagerTest.php
Labels: BC Break, Enhancement

#316 Refactor `ISBN` validator
  docs/book/v3/validators/isbn.md
  psalm-baseline.xml
  src/Isbn.php
  src/Isbn/Isbn10.php
  src/Isbn/Isbn13.php
  test/IsbnTest.php
Labels: BC Break, Documentation, Enhancement

#317 `Isbn` deprecations
  psalm-baseline.xml
  src/Isbn.php
  src/Isbn/Isbn10.php
  src/Isbn/Isbn13.php
Labels: Documentation, Feature Removal

#319 Deprecations for the `InArray` validator
  psalm-baseline.xml
  src/InArray.php
Labels: Documentation, Feature Removal

#318 Refactor `InArray` validator
  docs/book/v3/validators/in-array.md
  psalm-baseline.xml
  src/InArray.php
  test/InArrayTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#321 Deprecations for the `Identical` validator
  psalm-baseline.xml
  src/Identical.php
Labels: Documentation, Feature Removal

#320 Refactor `Identical` validator
  docs/book/v3/validators/identical.md
  psalm-baseline.xml
  src/Identical.php
  test/IdenticalTest.php
Labels: BC Break, Documentation, Enhancement

#323 `Iban` deprecations
  psalm-baseline.xml
  src/Iban.php
Labels: Documentation, Feature Removal

#322 Refactor `Iban` validator
  docs/book/v3/validators/iban.md
  psalm-baseline.xml
  src/Iban.php
  test/IbanTest.php
Labels: BC Break, Documentation, Enhancement

#329 Fix TLD updater script
  bin/update_hostname_validator.php
  psalm-baseline.xml
Labels: Bug, Enhancement

#326 `EmailAddress` validator deprecations
  psalm-baseline.xml
  src/EmailAddress.php
Labels: Documentation, Feature Removal

#328 `CreditCard` validator deprecations
  psalm-baseline.xml
  src/CreditCard.php
Labels: Documentation, Feature Removal

#327 Refactor `CreditCard` validator
  docs/book/v3/validators/credit-card.md
  psalm-baseline.xml
  src/CreditCard.php
  test/CreditCardTest.php
  test/TestAsset/CreditCardValidatorExtension.php
Labels: BC Break, Bug, Documentation, Enhancement

#324 Refactor `EmailAddress` Validator
  docs/book/v3/validators/email-address.md
  psalm-baseline.xml
  src/EmailAddress.php
  test/EmailAddressTest.php
Labels: BC Break, Documentation, Enhancement

#331 `Date` and `DateStep` Deprecations
  psalm-baseline.xml
  src/Date.php
  src/DateStep.php
Labels: Documentation, Feature Removal

#333 `IsJsonString` Deprecations
  psalm-baseline.xml
  src/IsJsonString.php
Labels: Documentation, Feature Removal

#332 Refactor `IsJsonString`
  docs/book/v3/validators/is-json-string.md
  psalm-baseline.xml
  src/IsJsonString.php
  test/IsJsonStringTest.php
Labels: BC Break, Documentation, Enhancement

#334 Minor SA Fixes
  psalm-baseline.xml
  src/Barcode/Code128.php
  src/Barcode/Code93.php
  src/Barcode/Issn.php
Labels: Enhancement

#335 Add precise types to `ConfigProvider` and `Module`
  src/ConfigProvider.php
  src/Module.php
Labels: BC Break, Documentation, Enhancement

#337 Cleanup Sitemap Related Validators
  psalm-baseline.xml
  src/Sitemap/Changefreq.php
  src/Sitemap/Lastmod.php
  src/Sitemap/Loc.php
  src/Sitemap/Priority.php
  test/Sitemap/LastmodTest.php
Labels: Documentation, Enhancement

#338 Remove unused exception classes
  psalm-baseline.xml
  src/Exception/BadMethodCallException.php
  src/Exception/ExtensionNotLoadedException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/InvalidMagicMimeFileException.php
  src/Exception/RuntimeException.php
Labels: BC Break, Enhancement

#339 Deprecate unused exceptions
  src/Exception/BadMethodCallException.php
  src/Exception/ExtensionNotLoadedException.php
Labels: Documentation, Feature Removal

#343 Deprecate setters and getters in File based validators
  psalm-baseline.xml
  src/File/Count.php
  src/File/Crc32.php
  src/File/Exists.php
  src/File/Extension.php
  src/File/FileInformationTrait.php
  src/File/Hash.php
  src/File/ImageSize.php
  src/File/Md5.php
  src/File/Sha1.php
  src/File/Size.php
  src/File/Upload.php
  src/File/WordCount.php
Labels: Documentation, Feature Removal

#341 Clean up usage of `$this->options`
  psalm-baseline.xml
  src/Ip.php
  src/NumberComparison.php
  src/StringLength.php
Labels: Enhancement

#342 `MimeType` deprecations
  psalm-baseline.xml
  src/Exception/InvalidMagicMimeFileException.php
  src/File/MimeType.php
Labels: Documentation, Feature Removal

#340 Refactor `MimeType` validator and descendants
  composer.json
  composer.lock
  docs/book/v3/validators/file/mime-type.md
  psalm-baseline.xml
  src/Exception/InvalidMagicMimeFileException.php
  src/File/ExcludeMimeType.php
  src/File/FileInformation.php
  src/File/IsCompressed.php
  src/File/IsImage.php
  src/File/MimeType.php
  test/File/ExcludeMimeTypeTest.php
  test/File/FileInformationTest.php
  test/File/IsCompressedTest.php
  test/File/IsImageTest.php
  test/File/MimeTypeTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#344 Remove libs from `suggest` that are already in `require`
  composer.json
Labels: Enhancement

#348 Refactor `Size` and `FilesSize` Validators
  docs/book/v3/validators/file/files-size.md
  docs/book/v3/validators/file/size.md
  psalm-baseline.xml
  src/File/Bytes.php
  src/File/FileInformation.php
  src/File/FilesSize.php
  src/File/Size.php
  test/File/BytesTest.php
  test/File/FileInformationTest.php
  test/File/FilesSizeTest.php
  test/File/SizeTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#345 Refactor `WordCount` validator
  docs/book/v3/validators/file/word-count.md
  psalm-baseline.xml
  src/File/WordCount.php
  test/File/WordCountTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#350 Refactor `ImageSize` validator
  docs/book/v3/validators/file/image-size.md
  psalm-baseline.xml
  src/File/ImageSize.php
  test/File/ImageSizeTest.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#352 Add type coverage badge to the readme
  README.md
Labels: Enhancement

#346 `UploadFile` validator cleanup
  docs/book/v3/validators/file/upload-file.md
  psalm-baseline.xml
  src/File/UploadFile.php
  test/File/UploadFileTest.php
Labels: BC Break, Documentation, Enhancement

#353 Deprecate Unnecessary File Hash Validators
  psalm-baseline.xml
  src/File/Crc32.php
  src/File/Md5.php
  src/File/Sha1.php
Labels: Documentation, Feature Removal

#354 Refactor `File\Hash` validator
  docs/book/v3/validators/file/crc32.md
  docs/book/v3/validators/file/hash.md
  docs/book/v3/validators/file/intro.md
  docs/book/v3/validators/file/md5.md
  docs/book/v3/validators/file/sha1.md
  mkdocs.yml
  psalm-baseline.xml
  src/File/Crc32.php
  src/File/Hash.php
  src/File/Md5.php
  src/File/Sha1.php
  src/ValidatorPluginManager.php
  test/File/Crc32Test.php
  test/File/HashTest.php
  test/File/Md5Test.php
  test/File/Sha1Test.php
  test/ValidatorPluginManagerCompatibilityTest.php
Labels: BC Break, Documentation, Enhancement

#351 Refactor `Exists` and `NotExists` validators
  docs/book/v3/validators/file/exists.md
  docs/book/v3/validators/file/not-exists.md
  psalm-baseline.xml
  src/File/Exists.php
  src/File/NotExists.php
  test/File/ExistsTest.php
  test/File/NotExistsTest.php
Labels: BC Break, Documentation, Enhancement

#356 Refactor file `Count` validator
  docs/book/v3/validators/file/count.md
  psalm-baseline.xml
  src/File/Count.php
  test/File/CountTest.php
Labels: BC Break, Documentation, Enhancement

#355 Refactor `Extension` and `ExcludeExtension` Validators
  docs/book/v3/validators/file/extension.md
  psalm-baseline.xml
  src/File/ExcludeExtension.php
  src/File/Extension.php
  src/File/FileInformationTrait.php
  test/File/ExcludeExtensionTest.php
  test/File/ExtensionTest.php
  test/File/FileInformationTraitTest.php
  test/File/TestAsset/FileInformation.php
Labels: BC Break, Documentation, Enhancement

#357 Remove unnecessary options declaration
  src/IsArray.php
Labels: Enhancement

#359 `AbstractValidator` deprecations
  psalm-baseline.xml
  src/AbstractValidator.php
  src/Translator/TranslatorAwareInterface.php
Labels: Documentation, Feature Removal

#360 Deprecate the legacy `Upload` validator
  psalm-baseline.xml
  src/File/Upload.php
Labels: Documentation, Feature Removal

#365 Enable `composer-require-checker` in CI
  .gitattributes
  composer-require-checker.json
  composer.json
  composer.lock
Labels: Enhancement

#362 Remove the legacy `Upload` validator
  docs/book/v3/validators/file/intro.md
  docs/book/v3/validators/file/upload.md
  mkdocs.yml
  psalm-baseline.xml
  src/File/Upload.php
  src/ValidatorPluginManager.php
  test/File/UploadTest.php
Labels: BC Break, Documentation

#368 Add test case for DKIM records
  test/HostnameTest.php
Labels: Enhancement

#369 Improve and correct doc-block comments for `AbstractValidator`
  src/AbstractValidator.php
Labels: Documentation, Enhancement

#361 Refactor `ValidatorChain`
  docs/book/v3/validator-chains.md
  psalm-baseline.xml
  src/ValidatorChain.php
  test/ValidatorChainTest.php
Labels: BC Break, Documentation, Enhancement, Review Needed

#372 Add `EnumCase` and `BackedEnumValue` Validators
  docs/book/v3/set.md
  docs/book/v3/validators/backed-enum-value.md
  docs/book/v3/validators/enum-case.md
  psalm-baseline.xml
  src/BackedEnumValue.php
  src/EnumCase.php
  src/ValidatorPluginManager.php
  test/BackedEnumValueTest.php
  test/EnumCaseTest.php
  test/TestAsset/ExampleIntBackedEnum.php
  test/TestAsset/ExampleStringBackedEnum.php
  test/TestAsset/ExampleUnitEnum.php
Labels: Documentation, Enhancement

#371 Add a simple factory for creating validator chains from configuration
  docs/book/v3/validator-chains.md
  src/ConfigProvider.php
  src/ValidatorChainFactory.php
  src/ValidatorChainFactoryFactory.php
  test/ValidatorChainFactoryFactoryTest.php
  test/ValidatorChainFactoryTest.php
Labels: Documentation, Enhancement

#373 Capitalize section headers in docs
  docs/book/v3/intro.md
  docs/book/v3/messages.md
  docs/book/v3/set.md
  docs/book/v3/validators/backed-enum-value.md
  docs/book/v3/validators/barcode.md
  docs/book/v3/validators/bic.md
  docs/book/v3/validators/callback.md
  docs/book/v3/validators/credit-card.md
  docs/book/v3/validators/date.md
  docs/book/v3/validators/digits.md
  docs/book/v3/validators/email-address.md
  docs/book/v3/validators/enum-case.md
  docs/book/v3/validators/explode.md
  docs/book/v3/validators/file/exclude-mime-type.md
  docs/book/v3/validators/file/exists.md
  docs/book/v3/validators/file/intro.md
  docs/book/v3/validators/file/mime-type.md
  docs/book/v3/validators/file/not-exists.md
  docs/book/v3/validators/hex.md
  docs/book/v3/validators/host-with-public-ipv4-address.md
  docs/book/v3/validators/hostname.md
  docs/book/v3/validators/iban.md
  docs/book/v3/validators/identical.md
  docs/book/v3/validators/in-array.md
  docs/book/v3/validators/ip.md
  docs/book/v3/validators/is-countable.md
  docs/book/v3/validators/isbn.md
  docs/book/v3/validators/isinstanceof.md
  docs/book/v3/validators/not-empty.md
  docs/book/v3/validators/regex.md
  docs/book/v3/validators/sitemap.md
  docs/book/v3/validators/step.md
  docs/book/v3/validators/string-length.md
  docs/book/v3/validators/undisclosed-password.md
  docs/book/v3/validators/uri.md
  docs/book/v3/validators/uuid.md
  docs/book/v3/writing-validators.md
Labels: Documentation, Enhancement

#376 Add missing nav links for new enum validators
  mkdocs.yml
Labels: Documentation

#378 Update validator documentation links in set.md
  docs/book/v3/set.md
Labels: Documentation, Enhancement

#374 Remove outdated version indicators from validator docs
  docs/book/v3/validators/is-array.md
  docs/book/v3/validators/undisclosed-password.md
  docs/book/v3/validators/uuid.md
Labels: Documentation, Enhancement

#375 Introduce `Conditional` validator
  docs/book/v3/set.md
  docs/book/v3/validators/conditional.md
  mkdocs.yml
  src/Conditional.php
  src/ConditionalFactory.php
  src/ValidatorChainFactory.php
  src/ValidatorPluginManager.php
  test/ConditionalFactoryTest.php
  test/ConditionalTest.php
Labels: Documentation, Enhancement, Feature Request, Review Needed

#379 Firm up Callback arguments and document `$context` parameter.
  docs/book/v3/validators/callback.md
  docs/book/v3/validators/credit-card.md
  src/Callback.php
  src/CreditCard.php
  test/CallbackTest.php
  test/CreditCardTest.php
Labels: BC Break, Documentation, Enhancement

#381 Add Support for PHP 8.4
  .laminas-ci.json
  .laminas-ci/pre-install.sh
  composer.json
  composer.lock
  psalm-baseline.xml
Labels: Enhancement

#383 Improve documentation of the `$context` parameter
  docs/book/v3/validator-chains.md
  docs/book/v3/validators/explode.md
  docs/book/v3/validators/identical.md
  docs/book/v3/writing-validators.md
Labels: Documentation, Enhancement
