Repository laminas/laminas-validator, pull requests merged in 2024-03, with the labels that each got.

#236 Add object to $value parameter of MimeType::isValid()
  src/File/ExcludeMimeType.php
  src/File/MimeType.php
Labels: Documentation, Enhancement

#239 Fix list indentation
  docs/book/validators/barcode.md
  docs/book/validators/email-address.md
  docs/book/validators/in-array.md
Labels: Documentation

#238 Add an IsArray Validator
  docs/book/set.md
  docs/book/validators/is-array.md
  mkdocs.yml
  psalm-baseline.xml
  src/IsArray.php
  src/ValidatorPluginManager.php
  test/Db/TestAsset/ConcreteDbValidator.php
  test/IsArrayTest.php
Labels: Enhancement, Feature Request
